-- AUTHOR
INSERT INTO AUTHOR (BRIEF) VALUES ('Пушкин А.С.');
INSERT INTO AUTHOR (BRIEF) VALUES ('Оруэл Д.');
INSERT INTO AUTHOR (BRIEF) VALUES ('Шекспир У.');

-- GENRE 
INSERT INTO GENRE (`NAME`) VALUES ('Сказка');
INSERT INTO GENRE (`NAME`) VALUES ('Фантастика');
INSERT INTO GENRE (`NAME`) VALUES ('Драмма');

-- BOOK 
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('Руслан и Людмила', 1);
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('1984', 2);
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('Ромео и Джульетта', 3);

-- BOOKGENRE 
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES (1, 1);
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES (1, 3);
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES (2, 2);
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES (2, 3);
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES (3, 3);



