DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID NUMERIC IDENTITY PRIMARY KEY, BRIEF VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID NUMERIC IDENTITY PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID NUMERIC IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHORID NUMERIC, FOREIGN KEY (AUTHORID) references AUTHOR(ID));

DROP TABLE IF EXISTS BOOKGENRE;
CREATE TABLE BOOKGENRE(ID NUMERIC IDENTITY PRIMARY KEY, BOOKID NUMERIC, GENREID NUMERIC, FOREIGN KEY (BOOKID) references BOOK(ID), FOREIGN KEY (GENREID) references GENRE(ID));