-- AUTHOR
INSERT INTO AUTHOR (BRIEF) VALUES ('Пушкин А.С.');
INSERT INTO AUTHOR (BRIEF) VALUES ('Оруэл Д.');
INSERT INTO AUTHOR (BRIEF) VALUES ('Шекспир У.');

-- GENRE 
INSERT INTO GENRE (`NAME`) VALUES ('Сказка');
INSERT INTO GENRE (`NAME`) VALUES ('Фантастика');
INSERT INTO GENRE (`NAME`) VALUES ('Драмма');

-- BOOK 
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('Руслан и Людмила' , (SELECT ID FROM AUTHOR WHERE BRIEF = 'Пушкин А.С.'));
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('1984'             , (SELECT ID FROM AUTHOR WHERE BRIEF = 'Оруэл Д.'));
INSERT INTO BOOK (TITLE, AUTHORID) VALUES ('Ромео и Джульетта', (SELECT ID FROM AUTHOR WHERE BRIEF = 'Шекспир У.'));

-- BOOKGENRE 
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES ((SELECT ID FROM BOOK WHERE TITLE = 'Руслан и Людмила') , (SELECT ID FROM GENRE WHERE `NAME` = 'Сказка'));
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES ((SELECT ID FROM BOOK WHERE TITLE = 'Руслан и Людмила') , (SELECT ID FROM GENRE WHERE `NAME` = 'Драмма'));
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES ((SELECT ID FROM BOOK WHERE TITLE = '1984')             , (SELECT ID FROM GENRE WHERE `NAME` = 'Фантастика'));
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES ((SELECT ID FROM BOOK WHERE TITLE = '1984')             , (SELECT ID FROM GENRE WHERE `NAME` = 'Драмма'));
INSERT INTO BOOKGENRE (BOOKID, GENREID) VALUES ((SELECT ID FROM BOOK WHERE TITLE = 'Ромео и Джульетта'), (SELECT ID FROM GENRE WHERE `NAME` = 'Драмма'));